#
# Arm SCP/MCP Software
# Copyright (c) 2024, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := CXL
BS_LIB_SOURCES = mod_cxl.c

include $(BS_DIR)/lib.mk
