/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockgicx00_reg.h"

static const char* CMockString_value = "value";
static const char* CMockString_write_icc_pmr = "write_icc_pmr";
static const char* CMockString_write_icc_sre = "write_icc_sre";
static const char* CMockString_write_igrpen0_el1 = "write_igrpen0_el1";

typedef struct _CMOCK_write_icc_sre_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_value;
  char IgnoreArg_value;

} CMOCK_write_icc_sre_CALL_INSTANCE;

typedef struct _CMOCK_write_igrpen0_el1_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_value;
  char IgnoreArg_value;

} CMOCK_write_igrpen0_el1_CALL_INSTANCE;

typedef struct _CMOCK_write_icc_pmr_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_value;
  char IgnoreArg_value;

} CMOCK_write_icc_pmr_CALL_INSTANCE;

static struct Mockgicx00_regInstance
{
  char write_icc_sre_IgnoreBool;
  char write_icc_sre_CallbackBool;
  CMOCK_write_icc_sre_CALLBACK write_icc_sre_CallbackFunctionPointer;
  int write_icc_sre_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_icc_sre_CallInstance;
  char write_igrpen0_el1_IgnoreBool;
  char write_igrpen0_el1_CallbackBool;
  CMOCK_write_igrpen0_el1_CALLBACK write_igrpen0_el1_CallbackFunctionPointer;
  int write_igrpen0_el1_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_igrpen0_el1_CallInstance;
  char write_icc_pmr_IgnoreBool;
  char write_icc_pmr_CallbackBool;
  CMOCK_write_icc_pmr_CALLBACK write_icc_pmr_CallbackFunctionPointer;
  int write_icc_pmr_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_icc_pmr_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockgicx00_reg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.write_icc_sre_CallInstance;
  if (Mock.write_icc_sre_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_icc_sre);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_icc_sre_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_igrpen0_el1_CallInstance;
  if (Mock.write_igrpen0_el1_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_igrpen0_el1);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_igrpen0_el1_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_icc_pmr_CallInstance;
  if (Mock.write_icc_pmr_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_icc_pmr);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_icc_pmr_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockgicx00_reg_Init(void)
{
  Mockgicx00_reg_Destroy();
}

void Mockgicx00_reg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void write_icc_sre(uint64_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_icc_sre_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_icc_sre);
  cmock_call_instance = (CMOCK_write_icc_sre_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_icc_sre_CallInstance);
  Mock.write_icc_sre_CallInstance = CMock_Guts_MemNext(Mock.write_icc_sre_CallInstance);
  if (Mock.write_icc_sre_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_icc_sre_CallbackBool &&
      Mock.write_icc_sre_CallbackFunctionPointer != NULL)
  {
    Mock.write_icc_sre_CallbackFunctionPointer(value, Mock.write_icc_sre_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_value)
  {
    UNITY_SET_DETAILS(CMockString_write_icc_sre,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_value), (void*)(&value), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_icc_sre_CallbackFunctionPointer != NULL)
  {
    Mock.write_icc_sre_CallbackFunctionPointer(value, Mock.write_icc_sre_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_icc_sre(CMOCK_write_icc_sre_CALL_INSTANCE* cmock_call_instance, uint64_t value);
void CMockExpectParameters_write_icc_sre(CMOCK_write_icc_sre_CALL_INSTANCE* cmock_call_instance, uint64_t value)
{
  memcpy((void*)(&cmock_call_instance->Expected_value), (void*)(&value),
         sizeof(uint64_t[sizeof(value) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_value = 0;
}

void write_icc_sre_CMockIgnore(void)
{
  Mock.write_icc_sre_IgnoreBool = (char)1;
}

void write_icc_sre_CMockStopIgnore(void)
{
  Mock.write_icc_sre_IgnoreBool = (char)0;
}

void write_icc_sre_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_icc_sre_CALL_INSTANCE));
  CMOCK_write_icc_sre_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_icc_sre_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_icc_sre_CallInstance = CMock_Guts_MemChain(Mock.write_icc_sre_CallInstance, cmock_guts_index);
  Mock.write_icc_sre_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_icc_sre_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t value)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_icc_sre_CALL_INSTANCE));
  CMOCK_write_icc_sre_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_icc_sre_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_icc_sre_CallInstance = CMock_Guts_MemChain(Mock.write_icc_sre_CallInstance, cmock_guts_index);
  Mock.write_icc_sre_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_icc_sre(cmock_call_instance, value);
}

void write_icc_sre_AddCallback(CMOCK_write_icc_sre_CALLBACK Callback)
{
  Mock.write_icc_sre_IgnoreBool = (char)0;
  Mock.write_icc_sre_CallbackBool = (char)1;
  Mock.write_icc_sre_CallbackFunctionPointer = Callback;
}

void write_icc_sre_Stub(CMOCK_write_icc_sre_CALLBACK Callback)
{
  Mock.write_icc_sre_IgnoreBool = (char)0;
  Mock.write_icc_sre_CallbackBool = (char)0;
  Mock.write_icc_sre_CallbackFunctionPointer = Callback;
}

void write_icc_sre_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_icc_sre_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_icc_sre_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_icc_sre_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value = 1;
}

void write_igrpen0_el1(uint64_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_igrpen0_el1_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_igrpen0_el1);
  cmock_call_instance = (CMOCK_write_igrpen0_el1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_igrpen0_el1_CallInstance);
  Mock.write_igrpen0_el1_CallInstance = CMock_Guts_MemNext(Mock.write_igrpen0_el1_CallInstance);
  if (Mock.write_igrpen0_el1_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_igrpen0_el1_CallbackBool &&
      Mock.write_igrpen0_el1_CallbackFunctionPointer != NULL)
  {
    Mock.write_igrpen0_el1_CallbackFunctionPointer(value, Mock.write_igrpen0_el1_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_value)
  {
    UNITY_SET_DETAILS(CMockString_write_igrpen0_el1,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_value), (void*)(&value), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_igrpen0_el1_CallbackFunctionPointer != NULL)
  {
    Mock.write_igrpen0_el1_CallbackFunctionPointer(value, Mock.write_igrpen0_el1_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_igrpen0_el1(CMOCK_write_igrpen0_el1_CALL_INSTANCE* cmock_call_instance, uint64_t value);
void CMockExpectParameters_write_igrpen0_el1(CMOCK_write_igrpen0_el1_CALL_INSTANCE* cmock_call_instance, uint64_t value)
{
  memcpy((void*)(&cmock_call_instance->Expected_value), (void*)(&value),
         sizeof(uint64_t[sizeof(value) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_value = 0;
}

void write_igrpen0_el1_CMockIgnore(void)
{
  Mock.write_igrpen0_el1_IgnoreBool = (char)1;
}

void write_igrpen0_el1_CMockStopIgnore(void)
{
  Mock.write_igrpen0_el1_IgnoreBool = (char)0;
}

void write_igrpen0_el1_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_igrpen0_el1_CALL_INSTANCE));
  CMOCK_write_igrpen0_el1_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_igrpen0_el1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_igrpen0_el1_CallInstance = CMock_Guts_MemChain(Mock.write_igrpen0_el1_CallInstance, cmock_guts_index);
  Mock.write_igrpen0_el1_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_igrpen0_el1_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t value)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_igrpen0_el1_CALL_INSTANCE));
  CMOCK_write_igrpen0_el1_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_igrpen0_el1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_igrpen0_el1_CallInstance = CMock_Guts_MemChain(Mock.write_igrpen0_el1_CallInstance, cmock_guts_index);
  Mock.write_igrpen0_el1_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_igrpen0_el1(cmock_call_instance, value);
}

void write_igrpen0_el1_AddCallback(CMOCK_write_igrpen0_el1_CALLBACK Callback)
{
  Mock.write_igrpen0_el1_IgnoreBool = (char)0;
  Mock.write_igrpen0_el1_CallbackBool = (char)1;
  Mock.write_igrpen0_el1_CallbackFunctionPointer = Callback;
}

void write_igrpen0_el1_Stub(CMOCK_write_igrpen0_el1_CALLBACK Callback)
{
  Mock.write_igrpen0_el1_IgnoreBool = (char)0;
  Mock.write_igrpen0_el1_CallbackBool = (char)0;
  Mock.write_igrpen0_el1_CallbackFunctionPointer = Callback;
}

void write_igrpen0_el1_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_igrpen0_el1_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_igrpen0_el1_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_igrpen0_el1_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value = 1;
}

void write_icc_pmr(uint64_t value)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_icc_pmr_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_icc_pmr);
  cmock_call_instance = (CMOCK_write_icc_pmr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_icc_pmr_CallInstance);
  Mock.write_icc_pmr_CallInstance = CMock_Guts_MemNext(Mock.write_icc_pmr_CallInstance);
  if (Mock.write_icc_pmr_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_icc_pmr_CallbackBool &&
      Mock.write_icc_pmr_CallbackFunctionPointer != NULL)
  {
    Mock.write_icc_pmr_CallbackFunctionPointer(value, Mock.write_icc_pmr_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_value)
  {
    UNITY_SET_DETAILS(CMockString_write_icc_pmr,CMockString_value);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_value), (void*)(&value), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_icc_pmr_CallbackFunctionPointer != NULL)
  {
    Mock.write_icc_pmr_CallbackFunctionPointer(value, Mock.write_icc_pmr_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_icc_pmr(CMOCK_write_icc_pmr_CALL_INSTANCE* cmock_call_instance, uint64_t value);
void CMockExpectParameters_write_icc_pmr(CMOCK_write_icc_pmr_CALL_INSTANCE* cmock_call_instance, uint64_t value)
{
  memcpy((void*)(&cmock_call_instance->Expected_value), (void*)(&value),
         sizeof(uint64_t[sizeof(value) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_value = 0;
}

void write_icc_pmr_CMockIgnore(void)
{
  Mock.write_icc_pmr_IgnoreBool = (char)1;
}

void write_icc_pmr_CMockStopIgnore(void)
{
  Mock.write_icc_pmr_IgnoreBool = (char)0;
}

void write_icc_pmr_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_icc_pmr_CALL_INSTANCE));
  CMOCK_write_icc_pmr_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_icc_pmr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_icc_pmr_CallInstance = CMock_Guts_MemChain(Mock.write_icc_pmr_CallInstance, cmock_guts_index);
  Mock.write_icc_pmr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_icc_pmr_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t value)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_icc_pmr_CALL_INSTANCE));
  CMOCK_write_icc_pmr_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_icc_pmr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_icc_pmr_CallInstance = CMock_Guts_MemChain(Mock.write_icc_pmr_CallInstance, cmock_guts_index);
  Mock.write_icc_pmr_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_icc_pmr(cmock_call_instance, value);
}

void write_icc_pmr_AddCallback(CMOCK_write_icc_pmr_CALLBACK Callback)
{
  Mock.write_icc_pmr_IgnoreBool = (char)0;
  Mock.write_icc_pmr_CallbackBool = (char)1;
  Mock.write_icc_pmr_CallbackFunctionPointer = Callback;
}

void write_icc_pmr_Stub(CMOCK_write_icc_pmr_CALLBACK Callback)
{
  Mock.write_icc_pmr_IgnoreBool = (char)0;
  Mock.write_icc_pmr_CallbackBool = (char)0;
  Mock.write_icc_pmr_CallbackFunctionPointer = Callback;
}

void write_icc_pmr_CMockIgnoreArg_value(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_icc_pmr_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_icc_pmr_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_icc_pmr_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_value = 1;
}

