/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_spmi_extra.h"

static const char* CMockString_dev_id = "dev_id";
static const char* CMockString_mod_spmi_driver_send_command = "mod_spmi_driver_send_command";
static const char* CMockString_request = "request";

typedef struct _CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_dev_id;
  struct mod_spmi_request* Expected_request;
  int Expected_request_Depth;
  char ReturnThruPtr_request_Used;
  struct mod_spmi_request* ReturnThruPtr_request_Val;
  size_t ReturnThruPtr_request_Size;
  char IgnoreArg_dev_id;
  char IgnoreArg_request;

} CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE;

static struct Mockmod_spmi_extraInstance
{
  char mod_spmi_driver_send_command_IgnoreBool;
  int mod_spmi_driver_send_command_FinalReturn;
  char mod_spmi_driver_send_command_CallbackBool;
  CMOCK_mod_spmi_driver_send_command_CALLBACK mod_spmi_driver_send_command_CallbackFunctionPointer;
  int mod_spmi_driver_send_command_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mod_spmi_driver_send_command_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_spmi_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.mod_spmi_driver_send_command_CallInstance;
  if (Mock.mod_spmi_driver_send_command_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mod_spmi_driver_send_command);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mod_spmi_driver_send_command_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_spmi_extra_Init(void)
{
  Mockmod_spmi_extra_Destroy();
}

void Mockmod_spmi_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int mod_spmi_driver_send_command(fwk_id_t dev_id, struct mod_spmi_request* request)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mod_spmi_driver_send_command);
  cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mod_spmi_driver_send_command_CallInstance);
  Mock.mod_spmi_driver_send_command_CallInstance = CMock_Guts_MemNext(Mock.mod_spmi_driver_send_command_CallInstance);
  if (Mock.mod_spmi_driver_send_command_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mod_spmi_driver_send_command_FinalReturn;
    Mock.mod_spmi_driver_send_command_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mod_spmi_driver_send_command_CallbackBool &&
      Mock.mod_spmi_driver_send_command_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mod_spmi_driver_send_command_CallbackFunctionPointer(dev_id, request, Mock.mod_spmi_driver_send_command_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_dev_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_spmi_driver_send_command,CMockString_dev_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_dev_id), (void*)(&dev_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_request)
  {
    UNITY_SET_DETAILS(CMockString_mod_spmi_driver_send_command,CMockString_request);
    if (cmock_call_instance->Expected_request == NULL)
      { UNITY_TEST_ASSERT_NULL(request, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_MEMORY_ARRAY((void*)(cmock_call_instance->Expected_request), (void*)(request), sizeof(struct mod_spmi_request), cmock_call_instance->Expected_request_Depth, cmock_line, CMockStringMismatch); }
  }
  }
  if (Mock.mod_spmi_driver_send_command_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mod_spmi_driver_send_command_CallbackFunctionPointer(dev_id, request, Mock.mod_spmi_driver_send_command_CallbackCalls++);
  }
  if (cmock_call_instance->ReturnThruPtr_request_Used)
  {
    UNITY_TEST_ASSERT_NOT_NULL(request, cmock_line, CMockStringPtrIsNULL);
    memcpy((void*)request, (void*)cmock_call_instance->ReturnThruPtr_request_Val,
      cmock_call_instance->ReturnThruPtr_request_Size);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mod_spmi_driver_send_command(CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance, fwk_id_t dev_id, struct mod_spmi_request* request, int request_Depth);
void CMockExpectParameters_mod_spmi_driver_send_command(CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance, fwk_id_t dev_id, struct mod_spmi_request* request, int request_Depth)
{
  memcpy((void*)(&cmock_call_instance->Expected_dev_id), (void*)(&dev_id),
         sizeof(fwk_id_t[sizeof(dev_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_dev_id = 0;
  cmock_call_instance->Expected_request = request;
  cmock_call_instance->Expected_request_Depth = request_Depth;
  cmock_call_instance->IgnoreArg_request = 0;
  cmock_call_instance->ReturnThruPtr_request_Used = 0;
}

void mod_spmi_driver_send_command_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE));
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_spmi_driver_send_command_CallInstance = CMock_Guts_MemChain(Mock.mod_spmi_driver_send_command_CallInstance, cmock_guts_index);
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)1;
}

void mod_spmi_driver_send_command_CMockStopIgnore(void)
{
  if(Mock.mod_spmi_driver_send_command_IgnoreBool)
    Mock.mod_spmi_driver_send_command_CallInstance = CMock_Guts_MemNext(Mock.mod_spmi_driver_send_command_CallInstance);
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
}

void mod_spmi_driver_send_command_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE));
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_spmi_driver_send_command_CallInstance = CMock_Guts_MemChain(Mock.mod_spmi_driver_send_command_CallInstance, cmock_guts_index);
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mod_spmi_driver_send_command_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t dev_id, struct mod_spmi_request* request, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE));
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_spmi_driver_send_command_CallInstance = CMock_Guts_MemChain(Mock.mod_spmi_driver_send_command_CallInstance, cmock_guts_index);
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_spmi_driver_send_command(cmock_call_instance, dev_id, request, 1);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_spmi_driver_send_command_AddCallback(CMOCK_mod_spmi_driver_send_command_CALLBACK Callback)
{
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
  Mock.mod_spmi_driver_send_command_CallbackBool = (char)1;
  Mock.mod_spmi_driver_send_command_CallbackFunctionPointer = Callback;
}

void mod_spmi_driver_send_command_Stub(CMOCK_mod_spmi_driver_send_command_CALLBACK Callback)
{
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
  Mock.mod_spmi_driver_send_command_CallbackBool = (char)0;
  Mock.mod_spmi_driver_send_command_CallbackFunctionPointer = Callback;
}

void mod_spmi_driver_send_command_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t dev_id, struct mod_spmi_request* request, int request_Depth, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE));
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_spmi_driver_send_command_CallInstance = CMock_Guts_MemChain(Mock.mod_spmi_driver_send_command_CallInstance, cmock_guts_index);
  Mock.mod_spmi_driver_send_command_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_spmi_driver_send_command(cmock_call_instance, dev_id, request, request_Depth);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_spmi_driver_send_command_CMockReturnMemThruPtr_request(UNITY_LINE_TYPE cmock_line, struct mod_spmi_request* request, size_t cmock_size)
{
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_spmi_driver_send_command_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringPtrPreExp);
  cmock_call_instance->ReturnThruPtr_request_Used = 1;
  cmock_call_instance->ReturnThruPtr_request_Val = request;
  cmock_call_instance->ReturnThruPtr_request_Size = cmock_size;
}

void mod_spmi_driver_send_command_CMockIgnoreArg_dev_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_spmi_driver_send_command_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_dev_id = 1;
}

void mod_spmi_driver_send_command_CMockIgnoreArg_request(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_spmi_driver_send_command_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_spmi_driver_send_command_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_request = 1;
}
