/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockarmv8r_mpu_reg.h"

static const char* CMockString_barrier_dsync_fence_full = "barrier_dsync_fence_full";
static const char* CMockString_barrier_isync_fence_full = "barrier_isync_fence_full";
static const char* CMockString_cmock_arg1 = "cmock_arg1";
static const char* CMockString_read_mair_el2 = "read_mair_el2";
static const char* CMockString_read_mpuir_el2 = "read_mpuir_el2";
static const char* CMockString_read_sctlr_el2 = "read_sctlr_el2";
static const char* CMockString_write_mair_el2 = "write_mair_el2";
static const char* CMockString_write_prbar_el2 = "write_prbar_el2";
static const char* CMockString_write_prlar_el2 = "write_prlar_el2";
static const char* CMockString_write_prselr_el2 = "write_prselr_el2";
static const char* CMockString_write_sctlr_el2 = "write_sctlr_el2";

typedef struct _CMOCK_read_mair_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t ReturnVal;

} CMOCK_read_mair_el2_CALL_INSTANCE;

typedef struct _CMOCK_write_mair_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_cmock_arg1;
  char IgnoreArg_cmock_arg1;

} CMOCK_write_mair_el2_CALL_INSTANCE;

typedef struct _CMOCK_read_mpuir_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t ReturnVal;

} CMOCK_read_mpuir_el2_CALL_INSTANCE;

typedef struct _CMOCK_write_prbar_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_cmock_arg1;
  char IgnoreArg_cmock_arg1;

} CMOCK_write_prbar_el2_CALL_INSTANCE;

typedef struct _CMOCK_write_prlar_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_cmock_arg1;
  char IgnoreArg_cmock_arg1;

} CMOCK_write_prlar_el2_CALL_INSTANCE;

typedef struct _CMOCK_write_prselr_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_cmock_arg1;
  char IgnoreArg_cmock_arg1;

} CMOCK_write_prselr_el2_CALL_INSTANCE;

typedef struct _CMOCK_read_sctlr_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t ReturnVal;

} CMOCK_read_sctlr_el2_CALL_INSTANCE;

typedef struct _CMOCK_write_sctlr_el2_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  uint64_t Expected_cmock_arg1;
  char IgnoreArg_cmock_arg1;

} CMOCK_write_sctlr_el2_CALL_INSTANCE;

typedef struct _CMOCK_barrier_dsync_fence_full_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_barrier_dsync_fence_full_CALL_INSTANCE;

typedef struct _CMOCK_barrier_isync_fence_full_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;

} CMOCK_barrier_isync_fence_full_CALL_INSTANCE;

static struct Mockarmv8r_mpu_regInstance
{
  char read_mair_el2_IgnoreBool;
  uint64_t read_mair_el2_FinalReturn;
  char read_mair_el2_CallbackBool;
  CMOCK_read_mair_el2_CALLBACK read_mair_el2_CallbackFunctionPointer;
  int read_mair_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE read_mair_el2_CallInstance;
  char write_mair_el2_IgnoreBool;
  char write_mair_el2_CallbackBool;
  CMOCK_write_mair_el2_CALLBACK write_mair_el2_CallbackFunctionPointer;
  int write_mair_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_mair_el2_CallInstance;
  char read_mpuir_el2_IgnoreBool;
  uint64_t read_mpuir_el2_FinalReturn;
  char read_mpuir_el2_CallbackBool;
  CMOCK_read_mpuir_el2_CALLBACK read_mpuir_el2_CallbackFunctionPointer;
  int read_mpuir_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE read_mpuir_el2_CallInstance;
  char write_prbar_el2_IgnoreBool;
  char write_prbar_el2_CallbackBool;
  CMOCK_write_prbar_el2_CALLBACK write_prbar_el2_CallbackFunctionPointer;
  int write_prbar_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_prbar_el2_CallInstance;
  char write_prlar_el2_IgnoreBool;
  char write_prlar_el2_CallbackBool;
  CMOCK_write_prlar_el2_CALLBACK write_prlar_el2_CallbackFunctionPointer;
  int write_prlar_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_prlar_el2_CallInstance;
  char write_prselr_el2_IgnoreBool;
  char write_prselr_el2_CallbackBool;
  CMOCK_write_prselr_el2_CALLBACK write_prselr_el2_CallbackFunctionPointer;
  int write_prselr_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_prselr_el2_CallInstance;
  char read_sctlr_el2_IgnoreBool;
  uint64_t read_sctlr_el2_FinalReturn;
  char read_sctlr_el2_CallbackBool;
  CMOCK_read_sctlr_el2_CALLBACK read_sctlr_el2_CallbackFunctionPointer;
  int read_sctlr_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE read_sctlr_el2_CallInstance;
  char write_sctlr_el2_IgnoreBool;
  char write_sctlr_el2_CallbackBool;
  CMOCK_write_sctlr_el2_CALLBACK write_sctlr_el2_CallbackFunctionPointer;
  int write_sctlr_el2_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE write_sctlr_el2_CallInstance;
  char barrier_dsync_fence_full_IgnoreBool;
  char barrier_dsync_fence_full_CallbackBool;
  CMOCK_barrier_dsync_fence_full_CALLBACK barrier_dsync_fence_full_CallbackFunctionPointer;
  int barrier_dsync_fence_full_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE barrier_dsync_fence_full_CallInstance;
  char barrier_isync_fence_full_IgnoreBool;
  char barrier_isync_fence_full_CallbackBool;
  CMOCK_barrier_isync_fence_full_CALLBACK barrier_isync_fence_full_CallbackFunctionPointer;
  int barrier_isync_fence_full_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE barrier_isync_fence_full_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockarmv8r_mpu_reg_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.read_mair_el2_CallInstance;
  if (Mock.read_mair_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_read_mair_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.read_mair_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_mair_el2_CallInstance;
  if (Mock.write_mair_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_mair_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_mair_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.read_mpuir_el2_CallInstance;
  if (Mock.read_mpuir_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_read_mpuir_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.read_mpuir_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_prbar_el2_CallInstance;
  if (Mock.write_prbar_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_prbar_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_prbar_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_prlar_el2_CallInstance;
  if (Mock.write_prlar_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_prlar_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_prlar_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_prselr_el2_CallInstance;
  if (Mock.write_prselr_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_prselr_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_prselr_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.read_sctlr_el2_CallInstance;
  if (Mock.read_sctlr_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_read_sctlr_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.read_sctlr_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.write_sctlr_el2_CallInstance;
  if (Mock.write_sctlr_el2_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_write_sctlr_el2);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.write_sctlr_el2_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.barrier_dsync_fence_full_CallInstance;
  if (Mock.barrier_dsync_fence_full_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_barrier_dsync_fence_full);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.barrier_dsync_fence_full_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.barrier_isync_fence_full_CallInstance;
  if (Mock.barrier_isync_fence_full_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_barrier_isync_fence_full);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.barrier_isync_fence_full_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockarmv8r_mpu_reg_Init(void)
{
  Mockarmv8r_mpu_reg_Destroy();
}

void Mockarmv8r_mpu_reg_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

uint64_t read_mair_el2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_read_mair_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_read_mair_el2);
  cmock_call_instance = (CMOCK_read_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.read_mair_el2_CallInstance);
  Mock.read_mair_el2_CallInstance = CMock_Guts_MemNext(Mock.read_mair_el2_CallInstance);
  if (Mock.read_mair_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.read_mair_el2_FinalReturn;
    memcpy((void*)(&Mock.read_mair_el2_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(uint64_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.read_mair_el2_CallbackBool &&
      Mock.read_mair_el2_CallbackFunctionPointer != NULL)
  {
    uint64_t cmock_cb_ret = Mock.read_mair_el2_CallbackFunctionPointer(Mock.read_mair_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.read_mair_el2_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.read_mair_el2_CallbackFunctionPointer(Mock.read_mair_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void read_mair_el2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_mair_el2_CALL_INSTANCE));
  CMOCK_read_mair_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_mair_el2_CallInstance = CMock_Guts_MemChain(Mock.read_mair_el2_CallInstance, cmock_guts_index);
  Mock.read_mair_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.read_mair_el2_IgnoreBool = (char)1;
}

void read_mair_el2_CMockStopIgnore(void)
{
  if(Mock.read_mair_el2_IgnoreBool)
    Mock.read_mair_el2_CallInstance = CMock_Guts_MemNext(Mock.read_mair_el2_CallInstance);
  Mock.read_mair_el2_IgnoreBool = (char)0;
}

void read_mair_el2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_mair_el2_CALL_INSTANCE));
  CMOCK_read_mair_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_mair_el2_CallInstance = CMock_Guts_MemChain(Mock.read_mair_el2_CallInstance, cmock_guts_index);
  Mock.read_mair_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(uint64_t[sizeof(cmock_to_return) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
}

void read_mair_el2_AddCallback(CMOCK_read_mair_el2_CALLBACK Callback)
{
  Mock.read_mair_el2_IgnoreBool = (char)0;
  Mock.read_mair_el2_CallbackBool = (char)1;
  Mock.read_mair_el2_CallbackFunctionPointer = Callback;
}

void read_mair_el2_Stub(CMOCK_read_mair_el2_CALLBACK Callback)
{
  Mock.read_mair_el2_IgnoreBool = (char)0;
  Mock.read_mair_el2_CallbackBool = (char)0;
  Mock.read_mair_el2_CallbackFunctionPointer = Callback;
}

void write_mair_el2(uint64_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_mair_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_mair_el2);
  cmock_call_instance = (CMOCK_write_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_mair_el2_CallInstance);
  Mock.write_mair_el2_CallInstance = CMock_Guts_MemNext(Mock.write_mair_el2_CallInstance);
  if (Mock.write_mair_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_mair_el2_CallbackBool &&
      Mock.write_mair_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_mair_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_mair_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_cmock_arg1)
  {
    UNITY_SET_DETAILS(CMockString_write_mair_el2,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_mair_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_mair_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_mair_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_mair_el2(CMOCK_write_mair_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1);
void CMockExpectParameters_write_mair_el2(CMOCK_write_mair_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1)
{
  memcpy((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1),
         sizeof(uint64_t[sizeof(cmock_arg1) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cmock_arg1 = 0;
}

void write_mair_el2_CMockIgnore(void)
{
  Mock.write_mair_el2_IgnoreBool = (char)1;
}

void write_mair_el2_CMockStopIgnore(void)
{
  Mock.write_mair_el2_IgnoreBool = (char)0;
}

void write_mair_el2_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_mair_el2_CALL_INSTANCE));
  CMOCK_write_mair_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_mair_el2_CallInstance = CMock_Guts_MemChain(Mock.write_mair_el2_CallInstance, cmock_guts_index);
  Mock.write_mair_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_mair_el2_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_mair_el2_CALL_INSTANCE));
  CMOCK_write_mair_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_mair_el2_CallInstance = CMock_Guts_MemChain(Mock.write_mair_el2_CallInstance, cmock_guts_index);
  Mock.write_mair_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_mair_el2(cmock_call_instance, cmock_arg1);
}

void write_mair_el2_AddCallback(CMOCK_write_mair_el2_CALLBACK Callback)
{
  Mock.write_mair_el2_IgnoreBool = (char)0;
  Mock.write_mair_el2_CallbackBool = (char)1;
  Mock.write_mair_el2_CallbackFunctionPointer = Callback;
}

void write_mair_el2_Stub(CMOCK_write_mair_el2_CALLBACK Callback)
{
  Mock.write_mair_el2_IgnoreBool = (char)0;
  Mock.write_mair_el2_CallbackBool = (char)0;
  Mock.write_mair_el2_CallbackFunctionPointer = Callback;
}

void write_mair_el2_CMockIgnoreArg_cmock_arg1(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_mair_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_mair_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_mair_el2_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cmock_arg1 = 1;
}

uint64_t read_mpuir_el2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_read_mpuir_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_read_mpuir_el2);
  cmock_call_instance = (CMOCK_read_mpuir_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.read_mpuir_el2_CallInstance);
  Mock.read_mpuir_el2_CallInstance = CMock_Guts_MemNext(Mock.read_mpuir_el2_CallInstance);
  if (Mock.read_mpuir_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.read_mpuir_el2_FinalReturn;
    memcpy((void*)(&Mock.read_mpuir_el2_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(uint64_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.read_mpuir_el2_CallbackBool &&
      Mock.read_mpuir_el2_CallbackFunctionPointer != NULL)
  {
    uint64_t cmock_cb_ret = Mock.read_mpuir_el2_CallbackFunctionPointer(Mock.read_mpuir_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.read_mpuir_el2_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.read_mpuir_el2_CallbackFunctionPointer(Mock.read_mpuir_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void read_mpuir_el2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_mpuir_el2_CALL_INSTANCE));
  CMOCK_read_mpuir_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_mpuir_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_mpuir_el2_CallInstance = CMock_Guts_MemChain(Mock.read_mpuir_el2_CallInstance, cmock_guts_index);
  Mock.read_mpuir_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.read_mpuir_el2_IgnoreBool = (char)1;
}

void read_mpuir_el2_CMockStopIgnore(void)
{
  if(Mock.read_mpuir_el2_IgnoreBool)
    Mock.read_mpuir_el2_CallInstance = CMock_Guts_MemNext(Mock.read_mpuir_el2_CallInstance);
  Mock.read_mpuir_el2_IgnoreBool = (char)0;
}

void read_mpuir_el2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_mpuir_el2_CALL_INSTANCE));
  CMOCK_read_mpuir_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_mpuir_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_mpuir_el2_CallInstance = CMock_Guts_MemChain(Mock.read_mpuir_el2_CallInstance, cmock_guts_index);
  Mock.read_mpuir_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(uint64_t[sizeof(cmock_to_return) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
}

void read_mpuir_el2_AddCallback(CMOCK_read_mpuir_el2_CALLBACK Callback)
{
  Mock.read_mpuir_el2_IgnoreBool = (char)0;
  Mock.read_mpuir_el2_CallbackBool = (char)1;
  Mock.read_mpuir_el2_CallbackFunctionPointer = Callback;
}

void read_mpuir_el2_Stub(CMOCK_read_mpuir_el2_CALLBACK Callback)
{
  Mock.read_mpuir_el2_IgnoreBool = (char)0;
  Mock.read_mpuir_el2_CallbackBool = (char)0;
  Mock.read_mpuir_el2_CallbackFunctionPointer = Callback;
}

void write_prbar_el2(uint64_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_prbar_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_prbar_el2);
  cmock_call_instance = (CMOCK_write_prbar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_prbar_el2_CallInstance);
  Mock.write_prbar_el2_CallInstance = CMock_Guts_MemNext(Mock.write_prbar_el2_CallInstance);
  if (Mock.write_prbar_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_prbar_el2_CallbackBool &&
      Mock.write_prbar_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_prbar_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_prbar_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_cmock_arg1)
  {
    UNITY_SET_DETAILS(CMockString_write_prbar_el2,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_prbar_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_prbar_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_prbar_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_prbar_el2(CMOCK_write_prbar_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1);
void CMockExpectParameters_write_prbar_el2(CMOCK_write_prbar_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1)
{
  memcpy((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1),
         sizeof(uint64_t[sizeof(cmock_arg1) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cmock_arg1 = 0;
}

void write_prbar_el2_CMockIgnore(void)
{
  Mock.write_prbar_el2_IgnoreBool = (char)1;
}

void write_prbar_el2_CMockStopIgnore(void)
{
  Mock.write_prbar_el2_IgnoreBool = (char)0;
}

void write_prbar_el2_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_prbar_el2_CALL_INSTANCE));
  CMOCK_write_prbar_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prbar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_prbar_el2_CallInstance = CMock_Guts_MemChain(Mock.write_prbar_el2_CallInstance, cmock_guts_index);
  Mock.write_prbar_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_prbar_el2_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_prbar_el2_CALL_INSTANCE));
  CMOCK_write_prbar_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prbar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_prbar_el2_CallInstance = CMock_Guts_MemChain(Mock.write_prbar_el2_CallInstance, cmock_guts_index);
  Mock.write_prbar_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_prbar_el2(cmock_call_instance, cmock_arg1);
}

void write_prbar_el2_AddCallback(CMOCK_write_prbar_el2_CALLBACK Callback)
{
  Mock.write_prbar_el2_IgnoreBool = (char)0;
  Mock.write_prbar_el2_CallbackBool = (char)1;
  Mock.write_prbar_el2_CallbackFunctionPointer = Callback;
}

void write_prbar_el2_Stub(CMOCK_write_prbar_el2_CALLBACK Callback)
{
  Mock.write_prbar_el2_IgnoreBool = (char)0;
  Mock.write_prbar_el2_CallbackBool = (char)0;
  Mock.write_prbar_el2_CallbackFunctionPointer = Callback;
}

void write_prbar_el2_CMockIgnoreArg_cmock_arg1(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_prbar_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prbar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_prbar_el2_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cmock_arg1 = 1;
}

void write_prlar_el2(uint64_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_prlar_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_prlar_el2);
  cmock_call_instance = (CMOCK_write_prlar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_prlar_el2_CallInstance);
  Mock.write_prlar_el2_CallInstance = CMock_Guts_MemNext(Mock.write_prlar_el2_CallInstance);
  if (Mock.write_prlar_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_prlar_el2_CallbackBool &&
      Mock.write_prlar_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_prlar_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_prlar_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_cmock_arg1)
  {
    UNITY_SET_DETAILS(CMockString_write_prlar_el2,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_prlar_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_prlar_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_prlar_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_prlar_el2(CMOCK_write_prlar_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1);
void CMockExpectParameters_write_prlar_el2(CMOCK_write_prlar_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1)
{
  memcpy((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1),
         sizeof(uint64_t[sizeof(cmock_arg1) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cmock_arg1 = 0;
}

void write_prlar_el2_CMockIgnore(void)
{
  Mock.write_prlar_el2_IgnoreBool = (char)1;
}

void write_prlar_el2_CMockStopIgnore(void)
{
  Mock.write_prlar_el2_IgnoreBool = (char)0;
}

void write_prlar_el2_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_prlar_el2_CALL_INSTANCE));
  CMOCK_write_prlar_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prlar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_prlar_el2_CallInstance = CMock_Guts_MemChain(Mock.write_prlar_el2_CallInstance, cmock_guts_index);
  Mock.write_prlar_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_prlar_el2_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_prlar_el2_CALL_INSTANCE));
  CMOCK_write_prlar_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prlar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_prlar_el2_CallInstance = CMock_Guts_MemChain(Mock.write_prlar_el2_CallInstance, cmock_guts_index);
  Mock.write_prlar_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_prlar_el2(cmock_call_instance, cmock_arg1);
}

void write_prlar_el2_AddCallback(CMOCK_write_prlar_el2_CALLBACK Callback)
{
  Mock.write_prlar_el2_IgnoreBool = (char)0;
  Mock.write_prlar_el2_CallbackBool = (char)1;
  Mock.write_prlar_el2_CallbackFunctionPointer = Callback;
}

void write_prlar_el2_Stub(CMOCK_write_prlar_el2_CALLBACK Callback)
{
  Mock.write_prlar_el2_IgnoreBool = (char)0;
  Mock.write_prlar_el2_CallbackBool = (char)0;
  Mock.write_prlar_el2_CallbackFunctionPointer = Callback;
}

void write_prlar_el2_CMockIgnoreArg_cmock_arg1(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_prlar_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prlar_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_prlar_el2_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cmock_arg1 = 1;
}

void write_prselr_el2(uint64_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_prselr_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_prselr_el2);
  cmock_call_instance = (CMOCK_write_prselr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_prselr_el2_CallInstance);
  Mock.write_prselr_el2_CallInstance = CMock_Guts_MemNext(Mock.write_prselr_el2_CallInstance);
  if (Mock.write_prselr_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_prselr_el2_CallbackBool &&
      Mock.write_prselr_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_prselr_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_prselr_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_cmock_arg1)
  {
    UNITY_SET_DETAILS(CMockString_write_prselr_el2,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_prselr_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_prselr_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_prselr_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_prselr_el2(CMOCK_write_prselr_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1);
void CMockExpectParameters_write_prselr_el2(CMOCK_write_prselr_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1)
{
  memcpy((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1),
         sizeof(uint64_t[sizeof(cmock_arg1) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cmock_arg1 = 0;
}

void write_prselr_el2_CMockIgnore(void)
{
  Mock.write_prselr_el2_IgnoreBool = (char)1;
}

void write_prselr_el2_CMockStopIgnore(void)
{
  Mock.write_prselr_el2_IgnoreBool = (char)0;
}

void write_prselr_el2_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_prselr_el2_CALL_INSTANCE));
  CMOCK_write_prselr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prselr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_prselr_el2_CallInstance = CMock_Guts_MemChain(Mock.write_prselr_el2_CallInstance, cmock_guts_index);
  Mock.write_prselr_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_prselr_el2_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_prselr_el2_CALL_INSTANCE));
  CMOCK_write_prselr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prselr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_prselr_el2_CallInstance = CMock_Guts_MemChain(Mock.write_prselr_el2_CallInstance, cmock_guts_index);
  Mock.write_prselr_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_prselr_el2(cmock_call_instance, cmock_arg1);
}

void write_prselr_el2_AddCallback(CMOCK_write_prselr_el2_CALLBACK Callback)
{
  Mock.write_prselr_el2_IgnoreBool = (char)0;
  Mock.write_prselr_el2_CallbackBool = (char)1;
  Mock.write_prselr_el2_CallbackFunctionPointer = Callback;
}

void write_prselr_el2_Stub(CMOCK_write_prselr_el2_CALLBACK Callback)
{
  Mock.write_prselr_el2_IgnoreBool = (char)0;
  Mock.write_prselr_el2_CallbackBool = (char)0;
  Mock.write_prselr_el2_CallbackFunctionPointer = Callback;
}

void write_prselr_el2_CMockIgnoreArg_cmock_arg1(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_prselr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_prselr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_prselr_el2_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cmock_arg1 = 1;
}

uint64_t read_sctlr_el2(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_read_sctlr_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_read_sctlr_el2);
  cmock_call_instance = (CMOCK_read_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.read_sctlr_el2_CallInstance);
  Mock.read_sctlr_el2_CallInstance = CMock_Guts_MemNext(Mock.read_sctlr_el2_CallInstance);
  if (Mock.read_sctlr_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.read_sctlr_el2_FinalReturn;
    memcpy((void*)(&Mock.read_sctlr_el2_FinalReturn), (void*)(&cmock_call_instance->ReturnVal),
         sizeof(uint64_t[sizeof(cmock_call_instance->ReturnVal) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.read_sctlr_el2_CallbackBool &&
      Mock.read_sctlr_el2_CallbackFunctionPointer != NULL)
  {
    uint64_t cmock_cb_ret = Mock.read_sctlr_el2_CallbackFunctionPointer(Mock.read_sctlr_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.read_sctlr_el2_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.read_sctlr_el2_CallbackFunctionPointer(Mock.read_sctlr_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void read_sctlr_el2_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_sctlr_el2_CALL_INSTANCE));
  CMOCK_read_sctlr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_sctlr_el2_CallInstance = CMock_Guts_MemChain(Mock.read_sctlr_el2_CallInstance, cmock_guts_index);
  Mock.read_sctlr_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.read_sctlr_el2_IgnoreBool = (char)1;
}

void read_sctlr_el2_CMockStopIgnore(void)
{
  if(Mock.read_sctlr_el2_IgnoreBool)
    Mock.read_sctlr_el2_CallInstance = CMock_Guts_MemNext(Mock.read_sctlr_el2_CallInstance);
  Mock.read_sctlr_el2_IgnoreBool = (char)0;
}

void read_sctlr_el2_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint64_t cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_read_sctlr_el2_CALL_INSTANCE));
  CMOCK_read_sctlr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_read_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.read_sctlr_el2_CallInstance = CMock_Guts_MemChain(Mock.read_sctlr_el2_CallInstance, cmock_guts_index);
  Mock.read_sctlr_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  memcpy((void*)(&cmock_call_instance->ReturnVal), (void*)(&cmock_to_return),
         sizeof(uint64_t[sizeof(cmock_to_return) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
}

void read_sctlr_el2_AddCallback(CMOCK_read_sctlr_el2_CALLBACK Callback)
{
  Mock.read_sctlr_el2_IgnoreBool = (char)0;
  Mock.read_sctlr_el2_CallbackBool = (char)1;
  Mock.read_sctlr_el2_CallbackFunctionPointer = Callback;
}

void read_sctlr_el2_Stub(CMOCK_read_sctlr_el2_CALLBACK Callback)
{
  Mock.read_sctlr_el2_IgnoreBool = (char)0;
  Mock.read_sctlr_el2_CallbackBool = (char)0;
  Mock.read_sctlr_el2_CallbackFunctionPointer = Callback;
}

void write_sctlr_el2(uint64_t cmock_arg1)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_write_sctlr_el2_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_write_sctlr_el2);
  cmock_call_instance = (CMOCK_write_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.write_sctlr_el2_CallInstance);
  Mock.write_sctlr_el2_CallInstance = CMock_Guts_MemNext(Mock.write_sctlr_el2_CallInstance);
  if (Mock.write_sctlr_el2_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.write_sctlr_el2_CallbackBool &&
      Mock.write_sctlr_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_sctlr_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_sctlr_el2_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_cmock_arg1)
  {
    UNITY_SET_DETAILS(CMockString_write_sctlr_el2,CMockString_cmock_arg1);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.write_sctlr_el2_CallbackFunctionPointer != NULL)
  {
    Mock.write_sctlr_el2_CallbackFunctionPointer(cmock_arg1, Mock.write_sctlr_el2_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void CMockExpectParameters_write_sctlr_el2(CMOCK_write_sctlr_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1);
void CMockExpectParameters_write_sctlr_el2(CMOCK_write_sctlr_el2_CALL_INSTANCE* cmock_call_instance, uint64_t cmock_arg1)
{
  memcpy((void*)(&cmock_call_instance->Expected_cmock_arg1), (void*)(&cmock_arg1),
         sizeof(uint64_t[sizeof(cmock_arg1) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_cmock_arg1 = 0;
}

void write_sctlr_el2_CMockIgnore(void)
{
  Mock.write_sctlr_el2_IgnoreBool = (char)1;
}

void write_sctlr_el2_CMockStopIgnore(void)
{
  Mock.write_sctlr_el2_IgnoreBool = (char)0;
}

void write_sctlr_el2_CMockExpectAnyArgs(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_sctlr_el2_CALL_INSTANCE));
  CMOCK_write_sctlr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_sctlr_el2_CallInstance = CMock_Guts_MemChain(Mock.write_sctlr_el2_CallInstance, cmock_guts_index);
  Mock.write_sctlr_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void write_sctlr_el2_CMockExpect(UNITY_LINE_TYPE cmock_line, uint64_t cmock_arg1)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_write_sctlr_el2_CALL_INSTANCE));
  CMOCK_write_sctlr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.write_sctlr_el2_CallInstance = CMock_Guts_MemChain(Mock.write_sctlr_el2_CallInstance, cmock_guts_index);
  Mock.write_sctlr_el2_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_write_sctlr_el2(cmock_call_instance, cmock_arg1);
}

void write_sctlr_el2_AddCallback(CMOCK_write_sctlr_el2_CALLBACK Callback)
{
  Mock.write_sctlr_el2_IgnoreBool = (char)0;
  Mock.write_sctlr_el2_CallbackBool = (char)1;
  Mock.write_sctlr_el2_CallbackFunctionPointer = Callback;
}

void write_sctlr_el2_Stub(CMOCK_write_sctlr_el2_CALLBACK Callback)
{
  Mock.write_sctlr_el2_IgnoreBool = (char)0;
  Mock.write_sctlr_el2_CallbackBool = (char)0;
  Mock.write_sctlr_el2_CallbackFunctionPointer = Callback;
}

void write_sctlr_el2_CMockIgnoreArg_cmock_arg1(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_write_sctlr_el2_CALL_INSTANCE* cmock_call_instance = (CMOCK_write_sctlr_el2_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.write_sctlr_el2_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_cmock_arg1 = 1;
}

void barrier_dsync_fence_full(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_barrier_dsync_fence_full_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_barrier_dsync_fence_full);
  cmock_call_instance = (CMOCK_barrier_dsync_fence_full_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.barrier_dsync_fence_full_CallInstance);
  Mock.barrier_dsync_fence_full_CallInstance = CMock_Guts_MemNext(Mock.barrier_dsync_fence_full_CallInstance);
  if (Mock.barrier_dsync_fence_full_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.barrier_dsync_fence_full_CallbackBool &&
      Mock.barrier_dsync_fence_full_CallbackFunctionPointer != NULL)
  {
    Mock.barrier_dsync_fence_full_CallbackFunctionPointer(Mock.barrier_dsync_fence_full_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.barrier_dsync_fence_full_CallbackFunctionPointer != NULL)
  {
    Mock.barrier_dsync_fence_full_CallbackFunctionPointer(Mock.barrier_dsync_fence_full_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void barrier_dsync_fence_full_CMockIgnore(void)
{
  Mock.barrier_dsync_fence_full_IgnoreBool = (char)1;
}

void barrier_dsync_fence_full_CMockStopIgnore(void)
{
  Mock.barrier_dsync_fence_full_IgnoreBool = (char)0;
}

void barrier_dsync_fence_full_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_barrier_dsync_fence_full_CALL_INSTANCE));
  CMOCK_barrier_dsync_fence_full_CALL_INSTANCE* cmock_call_instance = (CMOCK_barrier_dsync_fence_full_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.barrier_dsync_fence_full_CallInstance = CMock_Guts_MemChain(Mock.barrier_dsync_fence_full_CallInstance, cmock_guts_index);
  Mock.barrier_dsync_fence_full_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void barrier_dsync_fence_full_AddCallback(CMOCK_barrier_dsync_fence_full_CALLBACK Callback)
{
  Mock.barrier_dsync_fence_full_IgnoreBool = (char)0;
  Mock.barrier_dsync_fence_full_CallbackBool = (char)1;
  Mock.barrier_dsync_fence_full_CallbackFunctionPointer = Callback;
}

void barrier_dsync_fence_full_Stub(CMOCK_barrier_dsync_fence_full_CALLBACK Callback)
{
  Mock.barrier_dsync_fence_full_IgnoreBool = (char)0;
  Mock.barrier_dsync_fence_full_CallbackBool = (char)0;
  Mock.barrier_dsync_fence_full_CallbackFunctionPointer = Callback;
}

void barrier_isync_fence_full(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_barrier_isync_fence_full_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_barrier_isync_fence_full);
  cmock_call_instance = (CMOCK_barrier_isync_fence_full_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.barrier_isync_fence_full_CallInstance);
  Mock.barrier_isync_fence_full_CallInstance = CMock_Guts_MemNext(Mock.barrier_isync_fence_full_CallInstance);
  if (Mock.barrier_isync_fence_full_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    return;
  }
  if (!Mock.barrier_isync_fence_full_CallbackBool &&
      Mock.barrier_isync_fence_full_CallbackFunctionPointer != NULL)
  {
    Mock.barrier_isync_fence_full_CallbackFunctionPointer(Mock.barrier_isync_fence_full_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (Mock.barrier_isync_fence_full_CallbackFunctionPointer != NULL)
  {
    Mock.barrier_isync_fence_full_CallbackFunctionPointer(Mock.barrier_isync_fence_full_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
}

void barrier_isync_fence_full_CMockIgnore(void)
{
  Mock.barrier_isync_fence_full_IgnoreBool = (char)1;
}

void barrier_isync_fence_full_CMockStopIgnore(void)
{
  Mock.barrier_isync_fence_full_IgnoreBool = (char)0;
}

void barrier_isync_fence_full_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_barrier_isync_fence_full_CALL_INSTANCE));
  CMOCK_barrier_isync_fence_full_CALL_INSTANCE* cmock_call_instance = (CMOCK_barrier_isync_fence_full_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.barrier_isync_fence_full_CallInstance = CMock_Guts_MemChain(Mock.barrier_isync_fence_full_CallInstance, cmock_guts_index);
  Mock.barrier_isync_fence_full_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
}

void barrier_isync_fence_full_AddCallback(CMOCK_barrier_isync_fence_full_CALLBACK Callback)
{
  Mock.barrier_isync_fence_full_IgnoreBool = (char)0;
  Mock.barrier_isync_fence_full_CallbackBool = (char)1;
  Mock.barrier_isync_fence_full_CallbackFunctionPointer = Callback;
}

void barrier_isync_fence_full_Stub(CMOCK_barrier_isync_fence_full_CALLBACK Callback)
{
  Mock.barrier_isync_fence_full_IgnoreBool = (char)0;
  Mock.barrier_isync_fence_full_CallbackBool = (char)0;
  Mock.barrier_isync_fence_full_CallbackFunctionPointer = Callback;
}

