/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_scmi_power_domain_req_extra.h"

static const char* CMockString_alarm_id = "alarm_id";
static const char* CMockString_callback = "callback";
static const char* CMockString_fake_message_handler = "fake_message_handler";
static const char* CMockString_milliseconds = "milliseconds";
static const char* CMockString_param = "param";
static const char* CMockString_payload = "payload";
static const char* CMockString_payload_size = "payload_size";
static const char* CMockString_pd_id = "pd_id";
static const char* CMockString_report_power_state_transition = "report_power_state_transition";
static const char* CMockString_request_ack_by_interrupt = "request_ack_by_interrupt";
static const char* CMockString_response_message_handler = "response_message_handler";
static const char* CMockString_scmi_message_id = "scmi_message_id";
static const char* CMockString_scmi_protocol_id = "scmi_protocol_id";
static const char* CMockString_scmi_send_message = "scmi_send_message";
static const char* CMockString_service_id = "service_id";
static const char* CMockString_start_alarm_api = "start_alarm_api";
static const char* CMockString_state = "state";
static const char* CMockString_stop_alarm_api = "stop_alarm_api";
static const char* CMockString_token = "token";
static const char* CMockString_type = "type";

typedef struct _CMOCK_scmi_send_message_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  uint8_t Expected_scmi_message_id;
  uint8_t Expected_scmi_protocol_id;
  uint8_t Expected_token;
  fwk_id_t Expected_service_id;
  const void* Expected_payload;
  size_t Expected_payload_size;
  bool Expected_request_ack_by_interrupt;
  int Expected_payload_Depth;
  char IgnoreArg_scmi_message_id;
  char IgnoreArg_scmi_protocol_id;
  char IgnoreArg_token;
  char IgnoreArg_service_id;
  char IgnoreArg_payload;
  char IgnoreArg_payload_size;
  char IgnoreArg_request_ack_by_interrupt;

} CMOCK_scmi_send_message_CALL_INSTANCE;

typedef struct _CMOCK_response_message_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_service_id;
  char IgnoreArg_service_id;

} CMOCK_response_message_handler_CALL_INSTANCE;

typedef struct _CMOCK_report_power_state_transition_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_pd_id;
  unsigned int Expected_state;
  char IgnoreArg_pd_id;
  char IgnoreArg_state;

} CMOCK_report_power_state_transition_CALL_INSTANCE;

typedef struct _CMOCK_start_alarm_api_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_alarm_id;
  unsigned int Expected_milliseconds;
  enum mod_timer_alarm_type Expected_type;
  cmock_mod_scmi_power_domain_req_extra_func_ptr1 Expected_callback;
  uintptr_t Expected_param;
  char IgnoreArg_alarm_id;
  char IgnoreArg_milliseconds;
  char IgnoreArg_type;
  char IgnoreArg_callback;
  char IgnoreArg_param;

} CMOCK_start_alarm_api_CALL_INSTANCE;

typedef struct _CMOCK_stop_alarm_api_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_alarm_id;
  char IgnoreArg_alarm_id;

} CMOCK_stop_alarm_api_CALL_INSTANCE;

typedef struct _CMOCK_fake_message_handler_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_service_id;
  const void* Expected_payload;
  size_t Expected_payload_size;
  int Expected_payload_Depth;
  char IgnoreArg_service_id;
  char IgnoreArg_payload;
  char IgnoreArg_payload_size;

} CMOCK_fake_message_handler_CALL_INSTANCE;

static struct Mockmod_scmi_power_domain_req_extraInstance
{
  char scmi_send_message_IgnoreBool;
  int scmi_send_message_FinalReturn;
  char scmi_send_message_CallbackBool;
  CMOCK_scmi_send_message_CALLBACK scmi_send_message_CallbackFunctionPointer;
  int scmi_send_message_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE scmi_send_message_CallInstance;
  char response_message_handler_IgnoreBool;
  int response_message_handler_FinalReturn;
  char response_message_handler_CallbackBool;
  CMOCK_response_message_handler_CALLBACK response_message_handler_CallbackFunctionPointer;
  int response_message_handler_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE response_message_handler_CallInstance;
  char report_power_state_transition_IgnoreBool;
  int report_power_state_transition_FinalReturn;
  char report_power_state_transition_CallbackBool;
  CMOCK_report_power_state_transition_CALLBACK report_power_state_transition_CallbackFunctionPointer;
  int report_power_state_transition_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE report_power_state_transition_CallInstance;
  char start_alarm_api_IgnoreBool;
  int start_alarm_api_FinalReturn;
  char start_alarm_api_CallbackBool;
  CMOCK_start_alarm_api_CALLBACK start_alarm_api_CallbackFunctionPointer;
  int start_alarm_api_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE start_alarm_api_CallInstance;
  char stop_alarm_api_IgnoreBool;
  int stop_alarm_api_FinalReturn;
  char stop_alarm_api_CallbackBool;
  CMOCK_stop_alarm_api_CALLBACK stop_alarm_api_CallbackFunctionPointer;
  int stop_alarm_api_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE stop_alarm_api_CallInstance;
  char fake_message_handler_IgnoreBool;
  int fake_message_handler_FinalReturn;
  char fake_message_handler_CallbackBool;
  CMOCK_fake_message_handler_CALLBACK fake_message_handler_CallbackFunctionPointer;
  int fake_message_handler_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE fake_message_handler_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_scmi_power_domain_req_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.scmi_send_message_CallInstance;
  if (Mock.scmi_send_message_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_scmi_send_message);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.scmi_send_message_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.response_message_handler_CallInstance;
  if (Mock.response_message_handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_response_message_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.response_message_handler_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.report_power_state_transition_CallInstance;
  if (Mock.report_power_state_transition_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_report_power_state_transition);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.report_power_state_transition_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.start_alarm_api_CallInstance;
  if (Mock.start_alarm_api_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_start_alarm_api);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.start_alarm_api_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.stop_alarm_api_CallInstance;
  if (Mock.stop_alarm_api_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_stop_alarm_api);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.stop_alarm_api_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.fake_message_handler_CallInstance;
  if (Mock.fake_message_handler_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_fake_message_handler);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.fake_message_handler_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_scmi_power_domain_req_extra_Init(void)
{
  Mockmod_scmi_power_domain_req_extra_Destroy();
}

void Mockmod_scmi_power_domain_req_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int scmi_send_message(uint8_t scmi_message_id, uint8_t scmi_protocol_id, uint8_t token, fwk_id_t service_id, const void* payload, size_t payload_size, bool request_ack_by_interrupt)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_scmi_send_message);
  cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.scmi_send_message_CallInstance);
  Mock.scmi_send_message_CallInstance = CMock_Guts_MemNext(Mock.scmi_send_message_CallInstance);
  if (Mock.scmi_send_message_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.scmi_send_message_FinalReturn;
    Mock.scmi_send_message_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.scmi_send_message_CallbackBool &&
      Mock.scmi_send_message_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.scmi_send_message_CallbackFunctionPointer(scmi_message_id, scmi_protocol_id, token, service_id, payload, payload_size, request_ack_by_interrupt, Mock.scmi_send_message_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_scmi_message_id)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_scmi_message_id);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_scmi_message_id, scmi_message_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_scmi_protocol_id)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_scmi_protocol_id);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_scmi_protocol_id, scmi_protocol_id, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_token)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_token);
    UNITY_TEST_ASSERT_EQUAL_HEX8(cmock_call_instance->Expected_token, token, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_payload)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_payload);
    if (cmock_call_instance->Expected_payload == NULL)
      { UNITY_TEST_ASSERT_NULL(payload, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_payload, payload, cmock_call_instance->Expected_payload_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_payload_size)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_payload_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_payload_size), (void*)(&payload_size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_request_ack_by_interrupt)
  {
    UNITY_SET_DETAILS(CMockString_scmi_send_message,CMockString_request_ack_by_interrupt);
    UNITY_TEST_ASSERT_EQUAL_INT(cmock_call_instance->Expected_request_ack_by_interrupt, request_ack_by_interrupt, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.scmi_send_message_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.scmi_send_message_CallbackFunctionPointer(scmi_message_id, scmi_protocol_id, token, service_id, payload, payload_size, request_ack_by_interrupt, Mock.scmi_send_message_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_scmi_send_message(CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance, uint8_t scmi_message_id, uint8_t scmi_protocol_id, uint8_t token, fwk_id_t service_id, const void* payload, int payload_Depth, size_t payload_size, bool request_ack_by_interrupt);
void CMockExpectParameters_scmi_send_message(CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance, uint8_t scmi_message_id, uint8_t scmi_protocol_id, uint8_t token, fwk_id_t service_id, const void* payload, int payload_Depth, size_t payload_size, bool request_ack_by_interrupt)
{
  cmock_call_instance->Expected_scmi_message_id = scmi_message_id;
  cmock_call_instance->IgnoreArg_scmi_message_id = 0;
  cmock_call_instance->Expected_scmi_protocol_id = scmi_protocol_id;
  cmock_call_instance->IgnoreArg_scmi_protocol_id = 0;
  cmock_call_instance->Expected_token = token;
  cmock_call_instance->IgnoreArg_token = 0;
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
  cmock_call_instance->Expected_payload = payload;
  cmock_call_instance->Expected_payload_Depth = payload_Depth;
  cmock_call_instance->IgnoreArg_payload = 0;
  memcpy((void*)(&cmock_call_instance->Expected_payload_size), (void*)(&payload_size),
         sizeof(size_t[sizeof(payload_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_payload_size = 0;
  cmock_call_instance->Expected_request_ack_by_interrupt = request_ack_by_interrupt;
  cmock_call_instance->IgnoreArg_request_ack_by_interrupt = 0;
}

void scmi_send_message_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_send_message_CALL_INSTANCE));
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_send_message_CallInstance = CMock_Guts_MemChain(Mock.scmi_send_message_CallInstance, cmock_guts_index);
  Mock.scmi_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.scmi_send_message_IgnoreBool = (char)1;
}

void scmi_send_message_CMockStopIgnore(void)
{
  if(Mock.scmi_send_message_IgnoreBool)
    Mock.scmi_send_message_CallInstance = CMock_Guts_MemNext(Mock.scmi_send_message_CallInstance);
  Mock.scmi_send_message_IgnoreBool = (char)0;
}

void scmi_send_message_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_send_message_CALL_INSTANCE));
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_send_message_CallInstance = CMock_Guts_MemChain(Mock.scmi_send_message_CallInstance, cmock_guts_index);
  Mock.scmi_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void scmi_send_message_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t scmi_message_id, uint8_t scmi_protocol_id, uint8_t token, fwk_id_t service_id, const void* payload, size_t payload_size, bool request_ack_by_interrupt, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_send_message_CALL_INSTANCE));
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_send_message_CallInstance = CMock_Guts_MemChain(Mock.scmi_send_message_CallInstance, cmock_guts_index);
  Mock.scmi_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_scmi_send_message(cmock_call_instance, scmi_message_id, scmi_protocol_id, token, service_id, payload, payload_size, payload_size, request_ack_by_interrupt);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void scmi_send_message_AddCallback(CMOCK_scmi_send_message_CALLBACK Callback)
{
  Mock.scmi_send_message_IgnoreBool = (char)0;
  Mock.scmi_send_message_CallbackBool = (char)1;
  Mock.scmi_send_message_CallbackFunctionPointer = Callback;
}

void scmi_send_message_Stub(CMOCK_scmi_send_message_CALLBACK Callback)
{
  Mock.scmi_send_message_IgnoreBool = (char)0;
  Mock.scmi_send_message_CallbackBool = (char)0;
  Mock.scmi_send_message_CallbackFunctionPointer = Callback;
}

void scmi_send_message_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, uint8_t scmi_message_id, uint8_t scmi_protocol_id, uint8_t token, fwk_id_t service_id, const void* payload, int payload_Depth, size_t payload_size, bool request_ack_by_interrupt, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_scmi_send_message_CALL_INSTANCE));
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.scmi_send_message_CallInstance = CMock_Guts_MemChain(Mock.scmi_send_message_CallInstance, cmock_guts_index);
  Mock.scmi_send_message_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_scmi_send_message(cmock_call_instance, scmi_message_id, scmi_protocol_id, token, service_id, payload, payload_Depth, payload_size, request_ack_by_interrupt);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void scmi_send_message_CMockIgnoreArg_scmi_message_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_scmi_message_id = 1;
}

void scmi_send_message_CMockIgnoreArg_scmi_protocol_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_scmi_protocol_id = 1;
}

void scmi_send_message_CMockIgnoreArg_token(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_token = 1;
}

void scmi_send_message_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

void scmi_send_message_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload = 1;
}

void scmi_send_message_CMockIgnoreArg_payload_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload_size = 1;
}

void scmi_send_message_CMockIgnoreArg_request_ack_by_interrupt(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_scmi_send_message_CALL_INSTANCE* cmock_call_instance = (CMOCK_scmi_send_message_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.scmi_send_message_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_request_ack_by_interrupt = 1;
}

int response_message_handler(fwk_id_t service_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_response_message_handler);
  cmock_call_instance = (CMOCK_response_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.response_message_handler_CallInstance);
  Mock.response_message_handler_CallInstance = CMock_Guts_MemNext(Mock.response_message_handler_CallInstance);
  if (Mock.response_message_handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.response_message_handler_FinalReturn;
    Mock.response_message_handler_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.response_message_handler_CallbackBool &&
      Mock.response_message_handler_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.response_message_handler_CallbackFunctionPointer(service_id, Mock.response_message_handler_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_response_message_handler,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.response_message_handler_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.response_message_handler_CallbackFunctionPointer(service_id, Mock.response_message_handler_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_response_message_handler(CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id);
void CMockExpectParameters_response_message_handler(CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
}

void response_message_handler_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_response_message_handler_CALL_INSTANCE));
  CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_response_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.response_message_handler_CallInstance = CMock_Guts_MemChain(Mock.response_message_handler_CallInstance, cmock_guts_index);
  Mock.response_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.response_message_handler_IgnoreBool = (char)1;
}

void response_message_handler_CMockStopIgnore(void)
{
  if(Mock.response_message_handler_IgnoreBool)
    Mock.response_message_handler_CallInstance = CMock_Guts_MemNext(Mock.response_message_handler_CallInstance);
  Mock.response_message_handler_IgnoreBool = (char)0;
}

void response_message_handler_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_response_message_handler_CALL_INSTANCE));
  CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_response_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.response_message_handler_CallInstance = CMock_Guts_MemChain(Mock.response_message_handler_CallInstance, cmock_guts_index);
  Mock.response_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void response_message_handler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_response_message_handler_CALL_INSTANCE));
  CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_response_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.response_message_handler_CallInstance = CMock_Guts_MemChain(Mock.response_message_handler_CallInstance, cmock_guts_index);
  Mock.response_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_response_message_handler(cmock_call_instance, service_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void response_message_handler_AddCallback(CMOCK_response_message_handler_CALLBACK Callback)
{
  Mock.response_message_handler_IgnoreBool = (char)0;
  Mock.response_message_handler_CallbackBool = (char)1;
  Mock.response_message_handler_CallbackFunctionPointer = Callback;
}

void response_message_handler_Stub(CMOCK_response_message_handler_CALLBACK Callback)
{
  Mock.response_message_handler_IgnoreBool = (char)0;
  Mock.response_message_handler_CallbackBool = (char)0;
  Mock.response_message_handler_CallbackFunctionPointer = Callback;
}

void response_message_handler_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_response_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_response_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.response_message_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

int report_power_state_transition(fwk_id_t pd_id, unsigned int state)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_report_power_state_transition);
  cmock_call_instance = (CMOCK_report_power_state_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.report_power_state_transition_CallInstance);
  Mock.report_power_state_transition_CallInstance = CMock_Guts_MemNext(Mock.report_power_state_transition_CallInstance);
  if (Mock.report_power_state_transition_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.report_power_state_transition_FinalReturn;
    Mock.report_power_state_transition_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.report_power_state_transition_CallbackBool &&
      Mock.report_power_state_transition_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.report_power_state_transition_CallbackFunctionPointer(pd_id, state, Mock.report_power_state_transition_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_pd_id)
  {
    UNITY_SET_DETAILS(CMockString_report_power_state_transition,CMockString_pd_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_pd_id), (void*)(&pd_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_state)
  {
    UNITY_SET_DETAILS(CMockString_report_power_state_transition,CMockString_state);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_state, state, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.report_power_state_transition_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.report_power_state_transition_CallbackFunctionPointer(pd_id, state, Mock.report_power_state_transition_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_report_power_state_transition(CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance, fwk_id_t pd_id, unsigned int state);
void CMockExpectParameters_report_power_state_transition(CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance, fwk_id_t pd_id, unsigned int state)
{
  memcpy((void*)(&cmock_call_instance->Expected_pd_id), (void*)(&pd_id),
         sizeof(fwk_id_t[sizeof(pd_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_pd_id = 0;
  cmock_call_instance->Expected_state = state;
  cmock_call_instance->IgnoreArg_state = 0;
}

void report_power_state_transition_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_report_power_state_transition_CALL_INSTANCE));
  CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_report_power_state_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.report_power_state_transition_CallInstance = CMock_Guts_MemChain(Mock.report_power_state_transition_CallInstance, cmock_guts_index);
  Mock.report_power_state_transition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.report_power_state_transition_IgnoreBool = (char)1;
}

void report_power_state_transition_CMockStopIgnore(void)
{
  if(Mock.report_power_state_transition_IgnoreBool)
    Mock.report_power_state_transition_CallInstance = CMock_Guts_MemNext(Mock.report_power_state_transition_CallInstance);
  Mock.report_power_state_transition_IgnoreBool = (char)0;
}

void report_power_state_transition_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_report_power_state_transition_CALL_INSTANCE));
  CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_report_power_state_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.report_power_state_transition_CallInstance = CMock_Guts_MemChain(Mock.report_power_state_transition_CallInstance, cmock_guts_index);
  Mock.report_power_state_transition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void report_power_state_transition_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t pd_id, unsigned int state, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_report_power_state_transition_CALL_INSTANCE));
  CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_report_power_state_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.report_power_state_transition_CallInstance = CMock_Guts_MemChain(Mock.report_power_state_transition_CallInstance, cmock_guts_index);
  Mock.report_power_state_transition_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_report_power_state_transition(cmock_call_instance, pd_id, state);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void report_power_state_transition_AddCallback(CMOCK_report_power_state_transition_CALLBACK Callback)
{
  Mock.report_power_state_transition_IgnoreBool = (char)0;
  Mock.report_power_state_transition_CallbackBool = (char)1;
  Mock.report_power_state_transition_CallbackFunctionPointer = Callback;
}

void report_power_state_transition_Stub(CMOCK_report_power_state_transition_CALLBACK Callback)
{
  Mock.report_power_state_transition_IgnoreBool = (char)0;
  Mock.report_power_state_transition_CallbackBool = (char)0;
  Mock.report_power_state_transition_CallbackFunctionPointer = Callback;
}

void report_power_state_transition_CMockIgnoreArg_pd_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_report_power_state_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.report_power_state_transition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_pd_id = 1;
}

void report_power_state_transition_CMockIgnoreArg_state(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_report_power_state_transition_CALL_INSTANCE* cmock_call_instance = (CMOCK_report_power_state_transition_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.report_power_state_transition_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_state = 1;
}

int start_alarm_api(fwk_id_t alarm_id, unsigned int milliseconds, enum mod_timer_alarm_type type, cmock_mod_scmi_power_domain_req_extra_func_ptr1 callback, uintptr_t param)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_start_alarm_api);
  cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.start_alarm_api_CallInstance);
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemNext(Mock.start_alarm_api_CallInstance);
  if (Mock.start_alarm_api_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.start_alarm_api_FinalReturn;
    Mock.start_alarm_api_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.start_alarm_api_CallbackBool &&
      Mock.start_alarm_api_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.start_alarm_api_CallbackFunctionPointer(alarm_id, milliseconds, type, callback, param, Mock.start_alarm_api_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_alarm_id)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_alarm_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_alarm_id), (void*)(&alarm_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_milliseconds)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_milliseconds);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_milliseconds, milliseconds, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_type)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_type);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_type), (void*)(&type), sizeof(enum mod_timer_alarm_type), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_callback)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_callback);
    UNITY_TEST_ASSERT_EQUAL_PTR(cmock_call_instance->Expected_callback, callback, cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_param)
  {
    UNITY_SET_DETAILS(CMockString_start_alarm_api,CMockString_param);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_param), (void*)(&param), sizeof(uintptr_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.start_alarm_api_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.start_alarm_api_CallbackFunctionPointer(alarm_id, milliseconds, type, callback, param, Mock.start_alarm_api_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_start_alarm_api(CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance, fwk_id_t alarm_id, unsigned int milliseconds, enum mod_timer_alarm_type type, cmock_mod_scmi_power_domain_req_extra_func_ptr1 callback, uintptr_t param);
void CMockExpectParameters_start_alarm_api(CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance, fwk_id_t alarm_id, unsigned int milliseconds, enum mod_timer_alarm_type type, cmock_mod_scmi_power_domain_req_extra_func_ptr1 callback, uintptr_t param)
{
  memcpy((void*)(&cmock_call_instance->Expected_alarm_id), (void*)(&alarm_id),
         sizeof(fwk_id_t[sizeof(alarm_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_alarm_id = 0;
  cmock_call_instance->Expected_milliseconds = milliseconds;
  cmock_call_instance->IgnoreArg_milliseconds = 0;
  memcpy((void*)(&cmock_call_instance->Expected_type), (void*)(&type),
         sizeof(enum mod_timer_alarm_type[sizeof(type) == sizeof(enum mod_timer_alarm_type) ? 1 : -1])); /* add enum mod_timer_alarm_type to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_type = 0;
  memcpy((void*)(&cmock_call_instance->Expected_callback), (void*)(&callback),
         sizeof(cmock_mod_scmi_power_domain_req_extra_func_ptr1[sizeof(callback) == sizeof(cmock_mod_scmi_power_domain_req_extra_func_ptr1) ? 1 : -1])); /* add cmock_mod_scmi_power_domain_req_extra_func_ptr1 to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_callback = 0;
  memcpy((void*)(&cmock_call_instance->Expected_param), (void*)(&param),
         sizeof(uintptr_t[sizeof(param) == sizeof(uintptr_t) ? 1 : -1])); /* add uintptr_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_param = 0;
}

void start_alarm_api_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_alarm_api_CALL_INSTANCE));
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.start_alarm_api_CallInstance, cmock_guts_index);
  Mock.start_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.start_alarm_api_IgnoreBool = (char)1;
}

void start_alarm_api_CMockStopIgnore(void)
{
  if(Mock.start_alarm_api_IgnoreBool)
    Mock.start_alarm_api_CallInstance = CMock_Guts_MemNext(Mock.start_alarm_api_CallInstance);
  Mock.start_alarm_api_IgnoreBool = (char)0;
}

void start_alarm_api_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_alarm_api_CALL_INSTANCE));
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.start_alarm_api_CallInstance, cmock_guts_index);
  Mock.start_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void start_alarm_api_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t alarm_id, unsigned int milliseconds, enum mod_timer_alarm_type type, cmock_mod_scmi_power_domain_req_extra_func_ptr1 callback, uintptr_t param, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_start_alarm_api_CALL_INSTANCE));
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.start_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.start_alarm_api_CallInstance, cmock_guts_index);
  Mock.start_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_start_alarm_api(cmock_call_instance, alarm_id, milliseconds, type, callback, param);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void start_alarm_api_AddCallback(CMOCK_start_alarm_api_CALLBACK Callback)
{
  Mock.start_alarm_api_IgnoreBool = (char)0;
  Mock.start_alarm_api_CallbackBool = (char)1;
  Mock.start_alarm_api_CallbackFunctionPointer = Callback;
}

void start_alarm_api_Stub(CMOCK_start_alarm_api_CALLBACK Callback)
{
  Mock.start_alarm_api_IgnoreBool = (char)0;
  Mock.start_alarm_api_CallbackBool = (char)0;
  Mock.start_alarm_api_CallbackFunctionPointer = Callback;
}

void start_alarm_api_CMockIgnoreArg_alarm_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_alarm_id = 1;
}

void start_alarm_api_CMockIgnoreArg_milliseconds(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_milliseconds = 1;
}

void start_alarm_api_CMockIgnoreArg_type(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_type = 1;
}

void start_alarm_api_CMockIgnoreArg_callback(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_callback = 1;
}

void start_alarm_api_CMockIgnoreArg_param(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_start_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_start_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.start_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_param = 1;
}

int stop_alarm_api(fwk_id_t alarm_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_stop_alarm_api);
  cmock_call_instance = (CMOCK_stop_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.stop_alarm_api_CallInstance);
  Mock.stop_alarm_api_CallInstance = CMock_Guts_MemNext(Mock.stop_alarm_api_CallInstance);
  if (Mock.stop_alarm_api_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.stop_alarm_api_FinalReturn;
    Mock.stop_alarm_api_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.stop_alarm_api_CallbackBool &&
      Mock.stop_alarm_api_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.stop_alarm_api_CallbackFunctionPointer(alarm_id, Mock.stop_alarm_api_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_alarm_id)
  {
    UNITY_SET_DETAILS(CMockString_stop_alarm_api,CMockString_alarm_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_alarm_id), (void*)(&alarm_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.stop_alarm_api_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.stop_alarm_api_CallbackFunctionPointer(alarm_id, Mock.stop_alarm_api_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_stop_alarm_api(CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance, fwk_id_t alarm_id);
void CMockExpectParameters_stop_alarm_api(CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance, fwk_id_t alarm_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_alarm_id), (void*)(&alarm_id),
         sizeof(fwk_id_t[sizeof(alarm_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_alarm_id = 0;
}

void stop_alarm_api_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stop_alarm_api_CALL_INSTANCE));
  CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_stop_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stop_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.stop_alarm_api_CallInstance, cmock_guts_index);
  Mock.stop_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.stop_alarm_api_IgnoreBool = (char)1;
}

void stop_alarm_api_CMockStopIgnore(void)
{
  if(Mock.stop_alarm_api_IgnoreBool)
    Mock.stop_alarm_api_CallInstance = CMock_Guts_MemNext(Mock.stop_alarm_api_CallInstance);
  Mock.stop_alarm_api_IgnoreBool = (char)0;
}

void stop_alarm_api_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stop_alarm_api_CALL_INSTANCE));
  CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_stop_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stop_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.stop_alarm_api_CallInstance, cmock_guts_index);
  Mock.stop_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void stop_alarm_api_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t alarm_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_stop_alarm_api_CALL_INSTANCE));
  CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_stop_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.stop_alarm_api_CallInstance = CMock_Guts_MemChain(Mock.stop_alarm_api_CallInstance, cmock_guts_index);
  Mock.stop_alarm_api_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_stop_alarm_api(cmock_call_instance, alarm_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void stop_alarm_api_AddCallback(CMOCK_stop_alarm_api_CALLBACK Callback)
{
  Mock.stop_alarm_api_IgnoreBool = (char)0;
  Mock.stop_alarm_api_CallbackBool = (char)1;
  Mock.stop_alarm_api_CallbackFunctionPointer = Callback;
}

void stop_alarm_api_Stub(CMOCK_stop_alarm_api_CALLBACK Callback)
{
  Mock.stop_alarm_api_IgnoreBool = (char)0;
  Mock.stop_alarm_api_CallbackBool = (char)0;
  Mock.stop_alarm_api_CallbackFunctionPointer = Callback;
}

void stop_alarm_api_CMockIgnoreArg_alarm_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_stop_alarm_api_CALL_INSTANCE* cmock_call_instance = (CMOCK_stop_alarm_api_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.stop_alarm_api_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_alarm_id = 1;
}

int fake_message_handler(fwk_id_t service_id, const void* payload, size_t payload_size)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_fake_message_handler);
  cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.fake_message_handler_CallInstance);
  Mock.fake_message_handler_CallInstance = CMock_Guts_MemNext(Mock.fake_message_handler_CallInstance);
  if (Mock.fake_message_handler_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.fake_message_handler_FinalReturn;
    Mock.fake_message_handler_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.fake_message_handler_CallbackBool &&
      Mock.fake_message_handler_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.fake_message_handler_CallbackFunctionPointer(service_id, payload, payload_size, Mock.fake_message_handler_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_service_id)
  {
    UNITY_SET_DETAILS(CMockString_fake_message_handler,CMockString_service_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_payload)
  {
    UNITY_SET_DETAILS(CMockString_fake_message_handler,CMockString_payload);
    if (cmock_call_instance->Expected_payload == NULL)
      { UNITY_TEST_ASSERT_NULL(payload, cmock_line, CMockStringExpNULL); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX8_ARRAY(cmock_call_instance->Expected_payload, payload, cmock_call_instance->Expected_payload_Depth, cmock_line, CMockStringMismatch); }
  }
  if (!cmock_call_instance->IgnoreArg_payload_size)
  {
    UNITY_SET_DETAILS(CMockString_fake_message_handler,CMockString_payload_size);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_payload_size), (void*)(&payload_size), sizeof(size_t), cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.fake_message_handler_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.fake_message_handler_CallbackFunctionPointer(service_id, payload, payload_size, Mock.fake_message_handler_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_fake_message_handler(CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id, const void* payload, int payload_Depth, size_t payload_size);
void CMockExpectParameters_fake_message_handler(CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance, fwk_id_t service_id, const void* payload, int payload_Depth, size_t payload_size)
{
  memcpy((void*)(&cmock_call_instance->Expected_service_id), (void*)(&service_id),
         sizeof(fwk_id_t[sizeof(service_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_service_id = 0;
  cmock_call_instance->Expected_payload = payload;
  cmock_call_instance->Expected_payload_Depth = payload_Depth;
  cmock_call_instance->IgnoreArg_payload = 0;
  memcpy((void*)(&cmock_call_instance->Expected_payload_size), (void*)(&payload_size),
         sizeof(size_t[sizeof(payload_size) == sizeof(size_t) ? 1 : -1])); /* add size_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_payload_size = 0;
}

void fake_message_handler_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fake_message_handler_CALL_INSTANCE));
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fake_message_handler_CallInstance = CMock_Guts_MemChain(Mock.fake_message_handler_CallInstance, cmock_guts_index);
  Mock.fake_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.fake_message_handler_IgnoreBool = (char)1;
}

void fake_message_handler_CMockStopIgnore(void)
{
  if(Mock.fake_message_handler_IgnoreBool)
    Mock.fake_message_handler_CallInstance = CMock_Guts_MemNext(Mock.fake_message_handler_CallInstance);
  Mock.fake_message_handler_IgnoreBool = (char)0;
}

void fake_message_handler_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fake_message_handler_CALL_INSTANCE));
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fake_message_handler_CallInstance = CMock_Guts_MemChain(Mock.fake_message_handler_CallInstance, cmock_guts_index);
  Mock.fake_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void fake_message_handler_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, size_t payload_size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fake_message_handler_CALL_INSTANCE));
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fake_message_handler_CallInstance = CMock_Guts_MemChain(Mock.fake_message_handler_CallInstance, cmock_guts_index);
  Mock.fake_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fake_message_handler(cmock_call_instance, service_id, payload, payload_size, payload_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void fake_message_handler_AddCallback(CMOCK_fake_message_handler_CALLBACK Callback)
{
  Mock.fake_message_handler_IgnoreBool = (char)0;
  Mock.fake_message_handler_CallbackBool = (char)1;
  Mock.fake_message_handler_CallbackFunctionPointer = Callback;
}

void fake_message_handler_Stub(CMOCK_fake_message_handler_CALLBACK Callback)
{
  Mock.fake_message_handler_IgnoreBool = (char)0;
  Mock.fake_message_handler_CallbackBool = (char)0;
  Mock.fake_message_handler_CallbackFunctionPointer = Callback;
}

void fake_message_handler_CMockExpectWithArrayAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t service_id, const void* payload, int payload_Depth, size_t payload_size, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_fake_message_handler_CALL_INSTANCE));
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.fake_message_handler_CallInstance = CMock_Guts_MemChain(Mock.fake_message_handler_CallInstance, cmock_guts_index);
  Mock.fake_message_handler_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_fake_message_handler(cmock_call_instance, service_id, payload, payload_Depth, payload_size);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void fake_message_handler_CMockIgnoreArg_service_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.fake_message_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_service_id = 1;
}

void fake_message_handler_CMockIgnoreArg_payload(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.fake_message_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload = 1;
}

void fake_message_handler_CMockIgnoreArg_payload_size(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_fake_message_handler_CALL_INSTANCE* cmock_call_instance = (CMOCK_fake_message_handler_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.fake_message_handler_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_payload_size = 1;
}

