#
# Arm SCP/MCP Software
# Copyright (c) 2022, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := PLDM_FW
BS_LIB_SOURCES := mod_pldm_fw.c

include $(BS_DIR)/lib.mk
