#
# Arm SCP/MCP Software
# Copyright (c) 2018-2019, Arm Limited and Contributors. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

BS_LIB_NAME := MCTP_FW
BS_LIB_SOURCES := mod_mctp_fw.c

include $(BS_DIR)/lib.mk
