/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "cmock.h"
#include "Mockmod_dvfs_extra.h"

static const char* CMockString_clock_id = "clock_id";
static const char* CMockString_device_id = "device_id";
static const char* CMockString_mod_clock_api_set_rate = "mod_clock_api_set_rate";
static const char* CMockString_mod_psu_device_api_set_voltage = "mod_psu_device_api_set_voltage";
static const char* CMockString_rate = "rate";
static const char* CMockString_requester_id = "requester_id";
static const char* CMockString_round_mode = "round_mode";
static const char* CMockString_voltage = "voltage";

typedef struct _CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_device_id;
  uint32_t Expected_voltage;
  char IgnoreArg_device_id;
  char IgnoreArg_voltage;

} CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE;

typedef struct _CMOCK_mod_clock_api_set_rate_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  char ExpectAnyArgsBool;
  int ReturnVal;
  fwk_id_t Expected_clock_id;
  uint64_t Expected_rate;
  enum mod_clock_round_mode Expected_round_mode;
  unsigned int Expected_requester_id;
  char IgnoreArg_clock_id;
  char IgnoreArg_rate;
  char IgnoreArg_round_mode;
  char IgnoreArg_requester_id;

} CMOCK_mod_clock_api_set_rate_CALL_INSTANCE;

static struct Mockmod_dvfs_extraInstance
{
  char mod_psu_device_api_set_voltage_IgnoreBool;
  int mod_psu_device_api_set_voltage_FinalReturn;
  char mod_psu_device_api_set_voltage_CallbackBool;
  CMOCK_mod_psu_device_api_set_voltage_CALLBACK mod_psu_device_api_set_voltage_CallbackFunctionPointer;
  int mod_psu_device_api_set_voltage_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mod_psu_device_api_set_voltage_CallInstance;
  char mod_clock_api_set_rate_IgnoreBool;
  int mod_clock_api_set_rate_FinalReturn;
  char mod_clock_api_set_rate_CallbackBool;
  CMOCK_mod_clock_api_set_rate_CALLBACK mod_clock_api_set_rate_CallbackFunctionPointer;
  int mod_clock_api_set_rate_CallbackCalls;
  CMOCK_MEM_INDEX_TYPE mod_clock_api_set_rate_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void Mockmod_dvfs_extra_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_MEM_INDEX_TYPE call_instance;
  call_instance = Mock.mod_psu_device_api_set_voltage_CallInstance;
  if (Mock.mod_psu_device_api_set_voltage_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mod_psu_device_api_set_voltage);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
  call_instance = Mock.mod_clock_api_set_rate_CallInstance;
  if (Mock.mod_clock_api_set_rate_IgnoreBool)
    call_instance = CMOCK_GUTS_NONE;
  if (CMOCK_GUTS_NONE != call_instance)
  {
    UNITY_SET_DETAIL(CMockString_mod_clock_api_set_rate);
    UNITY_TEST_FAIL(cmock_line, CMockStringCalledLess);
  }
  if (Mock.mod_clock_api_set_rate_CallbackFunctionPointer != NULL)
  {
    call_instance = CMOCK_GUTS_NONE;
    (void)call_instance;
  }
}

void Mockmod_dvfs_extra_Init(void)
{
  Mockmod_dvfs_extra_Destroy();
}

void Mockmod_dvfs_extra_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

int mod_psu_device_api_set_voltage(fwk_id_t device_id, uint32_t voltage)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mod_psu_device_api_set_voltage);
  cmock_call_instance = (CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mod_psu_device_api_set_voltage_CallInstance);
  Mock.mod_psu_device_api_set_voltage_CallInstance = CMock_Guts_MemNext(Mock.mod_psu_device_api_set_voltage_CallInstance);
  if (Mock.mod_psu_device_api_set_voltage_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mod_psu_device_api_set_voltage_FinalReturn;
    Mock.mod_psu_device_api_set_voltage_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mod_psu_device_api_set_voltage_CallbackBool &&
      Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer(device_id, voltage, Mock.mod_psu_device_api_set_voltage_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_device_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_psu_device_api_set_voltage,CMockString_device_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_device_id), (void*)(&device_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_voltage)
  {
    UNITY_SET_DETAILS(CMockString_mod_psu_device_api_set_voltage,CMockString_voltage);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_voltage, voltage, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer(device_id, voltage, Mock.mod_psu_device_api_set_voltage_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mod_psu_device_api_set_voltage(CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance, fwk_id_t device_id, uint32_t voltage);
void CMockExpectParameters_mod_psu_device_api_set_voltage(CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance, fwk_id_t device_id, uint32_t voltage)
{
  memcpy((void*)(&cmock_call_instance->Expected_device_id), (void*)(&device_id),
         sizeof(fwk_id_t[sizeof(device_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_device_id = 0;
  cmock_call_instance->Expected_voltage = voltage;
  cmock_call_instance->IgnoreArg_voltage = 0;
}

void mod_psu_device_api_set_voltage_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE));
  CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_psu_device_api_set_voltage_CallInstance = CMock_Guts_MemChain(Mock.mod_psu_device_api_set_voltage_CallInstance, cmock_guts_index);
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)1;
}

void mod_psu_device_api_set_voltage_CMockStopIgnore(void)
{
  if(Mock.mod_psu_device_api_set_voltage_IgnoreBool)
    Mock.mod_psu_device_api_set_voltage_CallInstance = CMock_Guts_MemNext(Mock.mod_psu_device_api_set_voltage_CallInstance);
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)0;
}

void mod_psu_device_api_set_voltage_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE));
  CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_psu_device_api_set_voltage_CallInstance = CMock_Guts_MemChain(Mock.mod_psu_device_api_set_voltage_CallInstance, cmock_guts_index);
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mod_psu_device_api_set_voltage_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t device_id, uint32_t voltage, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE));
  CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_psu_device_api_set_voltage_CallInstance = CMock_Guts_MemChain(Mock.mod_psu_device_api_set_voltage_CallInstance, cmock_guts_index);
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_psu_device_api_set_voltage(cmock_call_instance, device_id, voltage);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_psu_device_api_set_voltage_AddCallback(CMOCK_mod_psu_device_api_set_voltage_CALLBACK Callback)
{
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)0;
  Mock.mod_psu_device_api_set_voltage_CallbackBool = (char)1;
  Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer = Callback;
}

void mod_psu_device_api_set_voltage_Stub(CMOCK_mod_psu_device_api_set_voltage_CALLBACK Callback)
{
  Mock.mod_psu_device_api_set_voltage_IgnoreBool = (char)0;
  Mock.mod_psu_device_api_set_voltage_CallbackBool = (char)0;
  Mock.mod_psu_device_api_set_voltage_CallbackFunctionPointer = Callback;
}

void mod_psu_device_api_set_voltage_CMockIgnoreArg_device_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_psu_device_api_set_voltage_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_device_id = 1;
}

void mod_psu_device_api_set_voltage_CMockIgnoreArg_voltage(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_psu_device_api_set_voltage_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_psu_device_api_set_voltage_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_voltage = 1;
}

int mod_clock_api_set_rate(fwk_id_t clock_id, uint64_t rate, enum mod_clock_round_mode round_mode, unsigned int requester_id)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance;
  UNITY_SET_DETAIL(CMockString_mod_clock_api_set_rate);
  cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.mod_clock_api_set_rate_CallInstance);
  Mock.mod_clock_api_set_rate_CallInstance = CMock_Guts_MemNext(Mock.mod_clock_api_set_rate_CallInstance);
  if (Mock.mod_clock_api_set_rate_IgnoreBool)
  {
    UNITY_CLR_DETAILS();
    if (cmock_call_instance == NULL)
      return Mock.mod_clock_api_set_rate_FinalReturn;
    Mock.mod_clock_api_set_rate_FinalReturn = cmock_call_instance->ReturnVal;
    return cmock_call_instance->ReturnVal;
  }
  if (!Mock.mod_clock_api_set_rate_CallbackBool &&
      Mock.mod_clock_api_set_rate_CallbackFunctionPointer != NULL)
  {
    int cmock_cb_ret = Mock.mod_clock_api_set_rate_CallbackFunctionPointer(clock_id, rate, round_mode, requester_id, Mock.mod_clock_api_set_rate_CallbackCalls++);
    UNITY_CLR_DETAILS();
    return cmock_cb_ret;
  }
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringCalledMore);
  cmock_line = cmock_call_instance->LineNumber;
  if (!cmock_call_instance->ExpectAnyArgsBool)
  {
  if (!cmock_call_instance->IgnoreArg_clock_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_clock_api_set_rate,CMockString_clock_id);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_clock_id), (void*)(&clock_id), sizeof(fwk_id_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_rate)
  {
    UNITY_SET_DETAILS(CMockString_mod_clock_api_set_rate,CMockString_rate);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_rate), (void*)(&rate), sizeof(uint64_t), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_round_mode)
  {
    UNITY_SET_DETAILS(CMockString_mod_clock_api_set_rate,CMockString_round_mode);
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_round_mode), (void*)(&round_mode), sizeof(enum mod_clock_round_mode), cmock_line, CMockStringMismatch);
  }
  if (!cmock_call_instance->IgnoreArg_requester_id)
  {
    UNITY_SET_DETAILS(CMockString_mod_clock_api_set_rate,CMockString_requester_id);
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_requester_id, requester_id, cmock_line, CMockStringMismatch);
  }
  }
  if (Mock.mod_clock_api_set_rate_CallbackFunctionPointer != NULL)
  {
    cmock_call_instance->ReturnVal = Mock.mod_clock_api_set_rate_CallbackFunctionPointer(clock_id, rate, round_mode, requester_id, Mock.mod_clock_api_set_rate_CallbackCalls++);
  }
  UNITY_CLR_DETAILS();
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_mod_clock_api_set_rate(CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance, fwk_id_t clock_id, uint64_t rate, enum mod_clock_round_mode round_mode, unsigned int requester_id);
void CMockExpectParameters_mod_clock_api_set_rate(CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance, fwk_id_t clock_id, uint64_t rate, enum mod_clock_round_mode round_mode, unsigned int requester_id)
{
  memcpy((void*)(&cmock_call_instance->Expected_clock_id), (void*)(&clock_id),
         sizeof(fwk_id_t[sizeof(clock_id) == sizeof(fwk_id_t) ? 1 : -1])); /* add fwk_id_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_clock_id = 0;
  memcpy((void*)(&cmock_call_instance->Expected_rate), (void*)(&rate),
         sizeof(uint64_t[sizeof(rate) == sizeof(uint64_t) ? 1 : -1])); /* add uint64_t to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_rate = 0;
  memcpy((void*)(&cmock_call_instance->Expected_round_mode), (void*)(&round_mode),
         sizeof(enum mod_clock_round_mode[sizeof(round_mode) == sizeof(enum mod_clock_round_mode) ? 1 : -1])); /* add enum mod_clock_round_mode to :treat_as_array if this causes an error */
  cmock_call_instance->IgnoreArg_round_mode = 0;
  cmock_call_instance->Expected_requester_id = requester_id;
  cmock_call_instance->IgnoreArg_requester_id = 0;
}

void mod_clock_api_set_rate_CMockIgnoreAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_clock_api_set_rate_CALL_INSTANCE));
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_clock_api_set_rate_CallInstance = CMock_Guts_MemChain(Mock.mod_clock_api_set_rate_CallInstance, cmock_guts_index);
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)1;
}

void mod_clock_api_set_rate_CMockStopIgnore(void)
{
  if(Mock.mod_clock_api_set_rate_IgnoreBool)
    Mock.mod_clock_api_set_rate_CallInstance = CMock_Guts_MemNext(Mock.mod_clock_api_set_rate_CallInstance);
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)0;
}

void mod_clock_api_set_rate_CMockExpectAnyArgsAndReturn(UNITY_LINE_TYPE cmock_line, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_clock_api_set_rate_CALL_INSTANCE));
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_clock_api_set_rate_CallInstance = CMock_Guts_MemChain(Mock.mod_clock_api_set_rate_CallInstance, cmock_guts_index);
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  cmock_call_instance->ReturnVal = cmock_to_return;
  cmock_call_instance->ExpectAnyArgsBool = (char)1;
}

void mod_clock_api_set_rate_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, fwk_id_t clock_id, uint64_t rate, enum mod_clock_round_mode round_mode, unsigned int requester_id, int cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_mod_clock_api_set_rate_CALL_INSTANCE));
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringOutOfMemory);
  memset(cmock_call_instance, 0, sizeof(*cmock_call_instance));
  Mock.mod_clock_api_set_rate_CallInstance = CMock_Guts_MemChain(Mock.mod_clock_api_set_rate_CallInstance, cmock_guts_index);
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)0;
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ExpectAnyArgsBool = (char)0;
  CMockExpectParameters_mod_clock_api_set_rate(cmock_call_instance, clock_id, rate, round_mode, requester_id);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void mod_clock_api_set_rate_AddCallback(CMOCK_mod_clock_api_set_rate_CALLBACK Callback)
{
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)0;
  Mock.mod_clock_api_set_rate_CallbackBool = (char)1;
  Mock.mod_clock_api_set_rate_CallbackFunctionPointer = Callback;
}

void mod_clock_api_set_rate_Stub(CMOCK_mod_clock_api_set_rate_CALLBACK Callback)
{
  Mock.mod_clock_api_set_rate_IgnoreBool = (char)0;
  Mock.mod_clock_api_set_rate_CallbackBool = (char)0;
  Mock.mod_clock_api_set_rate_CallbackFunctionPointer = Callback;
}

void mod_clock_api_set_rate_CMockIgnoreArg_clock_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_clock_api_set_rate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_clock_id = 1;
}

void mod_clock_api_set_rate_CMockIgnoreArg_rate(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_clock_api_set_rate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_rate = 1;
}

void mod_clock_api_set_rate_CMockIgnoreArg_round_mode(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_clock_api_set_rate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_round_mode = 1;
}

void mod_clock_api_set_rate_CMockIgnoreArg_requester_id(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_mod_clock_api_set_rate_CALL_INSTANCE* cmock_call_instance = (CMOCK_mod_clock_api_set_rate_CALL_INSTANCE*)CMock_Guts_GetAddressFor(CMock_Guts_MemEndOfChain(Mock.mod_clock_api_set_rate_CallInstance));
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, CMockStringIgnPreExp);
  cmock_call_instance->IgnoreArg_requester_id = 1;
}

